### ISSUE TITLE
New Electron Template

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable-templates#3]
[I created a template for electron](https://github.com/aolney/fable-template-electron):

`dotnet new -i Fable.Template.Electron`

`dotnet new fable-electron -n testelectron`

Should it live here or samples-electron?

@MangelMaxime @alfonsogarciacaro I listed you both as authors b/c I based off your templates; hope that's OK.

**Comment by alfonsogarciacaro** [comment]
Hi @aolney, this is great. Thanks for that! 😍 

I was thinking the `samples-XXX` repos should be something that users can clone and start playing with immediately, ideally also with a website so we can post it on the web (like [samples-pixi](http://fable.io/samples-pixi/)), because of that, I would say the template could go here so we can uniform distribution. But it's also ok if you keep the template in your profile and we add a link in the README of this repo. Whatever works best for you :smile:

BTW, can you please [send a PR to awesome-fable]() to add the template? Thanks again!
